version: '3'

services: 
  ml-app:
    build: 
      context: .
      dockerfile: Dockerfile.mlapp
    ports:
      - "5000:5000"
    volumes:
      - ./models:/app/models
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - MLFLOW_Tracking_URI=http://mlflow:5001     
    networks:
      - ml_network
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile.mlflow
    ports:
      - "5001:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    networks:
      - ml_network

networks:
    ml_network:
      driver: bridge
