train_data_path: "Food_Drive_2023_Processed.csv"
test_data_path: "Food_Drive_2024_Processed.csv"
models_dir: "models/"

random_forest:
  n_estimators: 100
  max_depth: 10

param_grids:
  Random_Forest:
    n_estimators: [50, 100, 200]
    max_depth: [5, 10, 20]
  Decision_Tree:
    max_depth: [3, 5, 10]

mlflow_experiment_name: "CMPT2500"
reports_dir: "reports/"
predictions_output: "predictions/Food_Drive_2024_Predictions.csv"
feature_importance: true
feature_columns:
  - "time_spent"
  - "doors_in_route"
  - "assessed_value"

target_column: "donation_bags_collected"

mlflow_experiment_name: "CMPT2500"
