test_data_path: "data/processed/Food_Drive_2024_Processed.csv"
models_dir: "models/"
reports_dir: "reports/"
predictions_output: "data/predictions/Food_Drive_2024_Predictions.csv"
feature_importance: true
feature_columns:
  - "time_spent"
  - "doors_in_route"
  - "assessed_value"

target_column: "donation_bags_collected"

mlflow_experiment_name: "CMPT2500"
